language: node_js
node_js:
  - 'node'

cache: npm

script: npm run build

deploy:
  repo: SWRTA-AI/swrta-ai.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
